# ==============================================================================
# ARCHIVO DE CONFIGURACIÓN DEL SERVIDOR REDIS-STYLE (C++20)
# ==============================================================================

# Puerto de escucha TCP
port 8080

# Cantidad de hilos trabajadores en el ThreadPool (0 = autodetectar núcleos de CPU)
threads 8

# Contraseña de autenticación requerida para los clientes (dejar vacío si no se desea AUTH)
# requirepass supersecreto123

# Persistencia en Disco (Append-Only File)
aof_enabled yes
aof_filename database.aof

# Límite máximo de claves antes de activar la política de desalojo LRU
max_keys 200000
